/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedStudentResultsRouteImport } from './routes/_authenticated/student/results'
import { Route as AuthenticatedStudentAnnouncementsRouteImport } from './routes/_authenticated/student/announcements'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSyllabusRouteImport } from './routes/_authenticated/admin/syllabus'
import { Route as AuthenticatedAdminQuestionsRouteImport } from './routes/_authenticated/admin/questions'
import { Route as AuthenticatedAdminLegalRouteImport } from './routes/_authenticated/admin/legal'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin/inbox'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin/exams'
import { Route as AuthenticatedAdminDepartmentsRouteImport } from './routes/_authenticated/admin/departments'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin/announcements'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin/inbox'
import { Route as AuthenticatedStudentExamSessionIdRouteImport } from './routes/_authenticated/student/exam.$sessionId'
import { Route as AuthenticatedAdminExamsSessionIdRouteImport } from './routes/_authenticated/admin/exams.$sessionId'
import { Route as AuthenticatedStudentExamSessionIdResultRouteImport } from './routes/_authenticated/student/exam.$sessionId.result'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentResultsRoute =
  AuthenticatedStudentResultsRouteImport.update({
    id: '/student/results',
    path: '/student/results',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentAnnouncementsRoute =
  AuthenticatedStudentAnnouncementsRouteImport.update({
    id: '/student/announcements',
    path: '/student/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSyllabusRoute =
  AuthenticatedAdminSyllabusRouteImport.update({
    id: '/admin/syllabus',
    path: '/admin/syllabus',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminQuestionsRoute =
  AuthenticatedAdminQuestionsRouteImport.update({
    id: '/admin/questions',
    path: '/admin/questions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLegalRoute = AuthenticatedAdminLegalRouteImport.update({
  id: '/admin/legal',
  path: '/admin/legal',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/admin/exams',
  path: '/admin/exams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDepartmentsRoute =
  AuthenticatedAdminDepartmentsRouteImport.update({
    id: '/admin/departments',
    path: '/admin/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/admin/announcements',
    path: '/admin/announcements',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentExamSessionIdRoute =
  AuthenticatedStudentExamSessionIdRouteImport.update({
    id: '/student/exam/$sessionId',
    path: '/student/exam/$sessionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminExamsSessionIdRoute =
  AuthenticatedAdminExamsSessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedStudentExamSessionIdResultRoute =
  AuthenticatedStudentExamSessionIdResultRouteImport.update({
    id: '/result',
    path: '/result',
    getParentRoute: () => AuthenticatedStudentExamSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/legal': typeof AuthenticatedAdminLegalRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/syllabus': typeof AuthenticatedAdminSyllabusRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/student/announcements': typeof AuthenticatedStudentAnnouncementsRoute
  '/student/results': typeof AuthenticatedStudentResultsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/student/': typeof AuthenticatedStudentIndexRoute
  '/admin/exams/$sessionId': typeof AuthenticatedAdminExamsSessionIdRoute
  '/student/exam/$sessionId': typeof AuthenticatedStudentExamSessionIdRouteWithChildren
  '/student/exam/$sessionId/result': typeof AuthenticatedStudentExamSessionIdResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/legal': typeof AuthenticatedAdminLegalRoute
  '/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/admin/syllabus': typeof AuthenticatedAdminSyllabusRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/student/announcements': typeof AuthenticatedStudentAnnouncementsRoute
  '/student/results': typeof AuthenticatedStudentResultsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/admin/exams/$sessionId': typeof AuthenticatedAdminExamsSessionIdRoute
  '/student/exam/$sessionId': typeof AuthenticatedStudentExamSessionIdRouteWithChildren
  '/student/exam/$sessionId/result': typeof AuthenticatedStudentExamSessionIdResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/departments': typeof AuthenticatedAdminDepartmentsRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/_authenticated/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/_authenticated/admin/legal': typeof AuthenticatedAdminLegalRoute
  '/_authenticated/admin/questions': typeof AuthenticatedAdminQuestionsRoute
  '/_authenticated/admin/syllabus': typeof AuthenticatedAdminSyllabusRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/student/announcements': typeof AuthenticatedStudentAnnouncementsRoute
  '/_authenticated/student/results': typeof AuthenticatedStudentResultsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/admin/exams/$sessionId': typeof AuthenticatedAdminExamsSessionIdRoute
  '/_authenticated/student/exam/$sessionId': typeof AuthenticatedStudentExamSessionIdRouteWithChildren
  '/_authenticated/student/exam/$sessionId/result': typeof AuthenticatedStudentExamSessionIdResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/verify-email'
    | '/settings'
    | '/admin/announcements'
    | '/admin/departments'
    | '/admin/exams'
    | '/admin/inbox'
    | '/admin/legal'
    | '/admin/questions'
    | '/admin/syllabus'
    | '/admin/users'
    | '/student/announcements'
    | '/student/results'
    | '/admin/'
    | '/student/'
    | '/admin/exams/$sessionId'
    | '/student/exam/$sessionId'
    | '/student/exam/$sessionId/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/verify-email'
    | '/settings'
    | '/admin/announcements'
    | '/admin/departments'
    | '/admin/exams'
    | '/admin/inbox'
    | '/admin/legal'
    | '/admin/questions'
    | '/admin/syllabus'
    | '/admin/users'
    | '/student/announcements'
    | '/student/results'
    | '/admin'
    | '/student'
    | '/admin/exams/$sessionId'
    | '/student/exam/$sessionId'
    | '/student/exam/$sessionId/result'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/settings'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/departments'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/inbox'
    | '/_authenticated/admin/legal'
    | '/_authenticated/admin/questions'
    | '/_authenticated/admin/syllabus'
    | '/_authenticated/admin/users'
    | '/_authenticated/student/announcements'
    | '/_authenticated/student/results'
    | '/_authenticated/admin/'
    | '/_authenticated/student/'
    | '/_authenticated/admin/exams/$sessionId'
    | '/_authenticated/student/exam/$sessionId'
    | '/_authenticated/student/exam/$sessionId/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/results': {
      id: '/_authenticated/student/results'
      path: '/student/results'
      fullPath: '/student/results'
      preLoaderRoute: typeof AuthenticatedStudentResultsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/announcements': {
      id: '/_authenticated/student/announcements'
      path: '/student/announcements'
      fullPath: '/student/announcements'
      preLoaderRoute: typeof AuthenticatedStudentAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/syllabus': {
      id: '/_authenticated/admin/syllabus'
      path: '/admin/syllabus'
      fullPath: '/admin/syllabus'
      preLoaderRoute: typeof AuthenticatedAdminSyllabusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/questions': {
      id: '/_authenticated/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AuthenticatedAdminQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/legal': {
      id: '/_authenticated/admin/legal'
      path: '/admin/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AuthenticatedAdminLegalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/inbox': {
      id: '/_authenticated/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AuthenticatedAdminInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/admin/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/departments': {
      id: '/_authenticated/admin/departments'
      path: '/admin/departments'
      fullPath: '/admin/departments'
      preLoaderRoute: typeof AuthenticatedAdminDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/admin/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/exam/$sessionId': {
      id: '/_authenticated/student/exam/$sessionId'
      path: '/student/exam/$sessionId'
      fullPath: '/student/exam/$sessionId'
      preLoaderRoute: typeof AuthenticatedStudentExamSessionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/exams/$sessionId': {
      id: '/_authenticated/admin/exams/$sessionId'
      path: '/$sessionId'
      fullPath: '/admin/exams/$sessionId'
      preLoaderRoute: typeof AuthenticatedAdminExamsSessionIdRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/student/exam/$sessionId/result': {
      id: '/_authenticated/student/exam/$sessionId/result'
      path: '/result'
      fullPath: '/student/exam/$sessionId/result'
      preLoaderRoute: typeof AuthenticatedStudentExamSessionIdResultRouteImport
      parentRoute: typeof AuthenticatedStudentExamSessionIdRoute
    }
  }
}

interface AuthenticatedAdminExamsRouteChildren {
  AuthenticatedAdminExamsSessionIdRoute: typeof AuthenticatedAdminExamsSessionIdRoute
}

const AuthenticatedAdminExamsRouteChildren: AuthenticatedAdminExamsRouteChildren =
  {
    AuthenticatedAdminExamsSessionIdRoute:
      AuthenticatedAdminExamsSessionIdRoute,
  }

const AuthenticatedAdminExamsRouteWithChildren =
  AuthenticatedAdminExamsRoute._addFileChildren(
    AuthenticatedAdminExamsRouteChildren,
  )

interface AuthenticatedStudentExamSessionIdRouteChildren {
  AuthenticatedStudentExamSessionIdResultRoute: typeof AuthenticatedStudentExamSessionIdResultRoute
}

const AuthenticatedStudentExamSessionIdRouteChildren: AuthenticatedStudentExamSessionIdRouteChildren =
  {
    AuthenticatedStudentExamSessionIdResultRoute:
      AuthenticatedStudentExamSessionIdResultRoute,
  }

const AuthenticatedStudentExamSessionIdRouteWithChildren =
  AuthenticatedStudentExamSessionIdRoute._addFileChildren(
    AuthenticatedStudentExamSessionIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminDepartmentsRoute: typeof AuthenticatedAdminDepartmentsRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRouteWithChildren
  AuthenticatedAdminInboxRoute: typeof AuthenticatedAdminInboxRoute
  AuthenticatedAdminLegalRoute: typeof AuthenticatedAdminLegalRoute
  AuthenticatedAdminQuestionsRoute: typeof AuthenticatedAdminQuestionsRoute
  AuthenticatedAdminSyllabusRoute: typeof AuthenticatedAdminSyllabusRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedStudentAnnouncementsRoute: typeof AuthenticatedStudentAnnouncementsRoute
  AuthenticatedStudentResultsRoute: typeof AuthenticatedStudentResultsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedStudentExamSessionIdRoute: typeof AuthenticatedStudentExamSessionIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminDepartmentsRoute: AuthenticatedAdminDepartmentsRoute,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRouteWithChildren,
  AuthenticatedAdminInboxRoute: AuthenticatedAdminInboxRoute,
  AuthenticatedAdminLegalRoute: AuthenticatedAdminLegalRoute,
  AuthenticatedAdminQuestionsRoute: AuthenticatedAdminQuestionsRoute,
  AuthenticatedAdminSyllabusRoute: AuthenticatedAdminSyllabusRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedStudentAnnouncementsRoute:
    AuthenticatedStudentAnnouncementsRoute,
  AuthenticatedStudentResultsRoute: AuthenticatedStudentResultsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedStudentExamSessionIdRoute:
    AuthenticatedStudentExamSessionIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
